openapi: 3.0.0
info:
  title: Minha API
  version: 1.0.0
  description: Descrição da minha API

paths:
  /users:
    get:
      summary: Lista usuários
      operationId: listUsers
      responses:
        "200":
          description: Ok
