  


server:
  port: 8082

spring:
  application.name:
  zipkin:
    baseUrl: http://127.0.0.1:9411/
    name: CrudAlunoDevops-0.0.1-SNAPSHOT
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  sleuth:
    sampler:
      probability: 1.0  
h2:
  console:
    enabled: true
    path: /h2
mvc:
   pathmatch:
     matching-strategy: ANT_PATH_MATCHER
main: 
   allow-circular-references: true
   


      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator   
      
  tracing:
    sleuth:
      sampler:
        probability: 1.0
  metrics:
    export:
      zipkin:
        enabled: true
        
        
        
logging.level.org.springframework.cloud.sleuth: DEBUG
              
       